services:
  - type: web
    name: eatoes-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://saikiranbeesa_db_user:A5iCqEPpKmeoAHzg@cluster0.ppgwaqn.mongodb.net/?appName=Cluster0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
